### ISSUE TITLE
    from mpi4py import MPI ImportError: DLL load failed

### ISSUE THREAD

**Issue by feiyangdezhu** [AI4Finance-LLC/FinRL-Library#1]
I operated according to your instructions, and all the packages are complete, but I don't know how to report this error! Give advice or comments please!

**Comment by BruceYanghy** [comment]
Did you use Windows environment? Currently the support of OpenAI for Windows is weak, everything works smoothly in macOS or directly ubuntu.

**Comment by BruceYanghy** [comment]
> I operated according to your instructions, and all the packages are complete, but I don't know how to report this error! Give advice or comments please!

Did you use Windows environment? Currently the support of OpenAI for Windows is weak, everything works smoothly in macOS or directly ubuntu.

**Comment by BruceYanghy** [comment]
https://stackoverflow.com/questions/14004457/error-loading-mpi-dll-in-mpi4py

openai/large-scale-curiosity#15

**Comment by stupefy007** [comment]
I tried ubuntu on Windows but still failed, only works in macOS.

ERROR: Command errored out with exit status 1: /home/zhuhx/FinRL-Library/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8llehrxw/mpi4py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8llehrxw/mpi4py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-72buf3c_/install-record.txt --single-version-externally-managed --compile --install-headers /home/zhuhx/FinRL-Library/venv/include/site/python3.6/mpi4py Check the logs for full command output.

**Comment by XiaoYangLiu-FinRL** [comment]
The detailed instructions for installation can be found here: https://ai4finance.medium.com/finrl-for-quantitative-finance-install-and-setup-tutorial-for-beginners-1db80ad39159
