### ISSUE TITLE
Setting random seed to reproduce the same results

### ISSUE THREAD

**Issue by dsimonov** [AI4Finance-LLC/FinRL-Library#10]
Is there a way to set the seed to get repeatable results?

**Comment by hust512** [comment]
DRL algorithms have randomness, it may be not appropriate to exactly repeat the results. Usually, we can compare the cumulated rewards vs. steps.  Let me know if you have a better way.

**Comment by hust512** [comment]
Later on, we would like to include logging and tracking modules, and maintain benchmark experiments, for comparing purpose.
