### ISSUE TITLE
Adj Close is used

### ISSUE THREAD

**Issue by noke8868** [AI4Finance-LLC/FinRL-Library#100]
hello, i checked your code and realized you are using 'Adj Close' as close price.
actually  Adj Close ( not sure yahoo used which adj way, assume adj forward), is implicative future function.
cannot use it for training and prediction.
and another strange thing is no matter what feature input given, the final result(enough training） are the same as buy&hold.
do you have clue? thanks

**Comment by XiaoYangLiu-FinRL** [comment]
"Adj close" price is reasonable choice, at least in backtestings. 

I believe the second issues have been fixed.
