### ISSUE TITLE
from finrl.model.models import DRLAgent,DRLEnsembleAgent

### ISSUE THREAD

**Issue by zcy-4747** [AI4Finance-LLC/FinRL-Library#101]
model  is no function DRLEnsembleAgent. so I can't to use
ensemble_agent = DRLEnsembleAgent(df=processed_full,
                 train_period=(train_start,train_end),
                 val_test_period=(val_test_start,val_test_end),
                 rebalance_window=rebalance_window,
                 validation_window=validation_window,
                 **env_kwargs)

**Comment by XiaoYangLiu-FinRL** [comment]
Could you please check the notebook: https://github.com/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_ensemble_stock_trading_ICAIF_2020.ipynb

**Comment by Rhea1918** [comment]
Unable to open the link

**Comment by MaximCamilleri** [comment]
Also cant open link

**Comment by ryan-durbin** [comment]
Also can't open link. Having same problem
