### ISSUE TITLE
FinRL_multiple_stock_trading.ipynb Error at Trading Section

### ISSUE THREAD

**Issue by Bowmangotti** [AI4Finance-LLC/FinRL-Library#102]
When executing this line (I used the a2c model):

``df_account_value, df_actions = DRLAgent.DRL_prediction(
    model=model_a2c, 
    environment = e_trade_gym)

an error is thrown:
ValueError: Length mismatch: Expected axis has 0 elements, new values have 1 elements

**Comment by Petcron** [comment]
Also getting the same error.

**Comment by Youbadawy** [comment]
Same

**Comment by Youbadawy** [comment]
So I have pinpointed the issue, but I am still trying to understand what is happening exactly with the code, if anyone has been involved in prior days and has a deeper understanding of the following methods, please do lend a hand! Inside the 

> ./finrl/env/env_stocktrading.py
The error is being caused by assigning a dataframe with length 0 with an index date length 1, does anyone know what the df_actions represents?

    def save_action_memory(self):
        if len(self.df.tic.unique())>1:
            # date and close price length must match actions length
            date_list = self.date_memory[:-1]
            df_date = pd.DataFrame(date_list)
            df_date.columns = ['date']
            action_list = self.actions_memory
            df_actions = pd.DataFrame(action_list)
            df_actions.columns = self.data.tic.values
            df_actions.index = df_date.date
            #df_actions = pd.DataFrame({'date':date_list,'actions':action_list})
        else:
            date_list = self.date_memory[:-1]
            action_list = self.actions_memory
            df_actions = pd.DataFrame({'date':date_list,'actions':action_list})
        return df_actions

**Comment by Tarun-Khilani** [comment]
Can you try to update to this and verify if it works
def save_action_memory(self):
        if len(self.df.tic.unique())>1:
            # date and close price length must match actions length
            date_list = self.date_memory[:-1]
            df_date = pd.DataFrame(date_list)
            df_date.rename(columns={0:'date'},inplace= True)
            action_list = self.actions_memory
            df_actions = pd.DataFrame(action_list)
            df_actions.rename(columns =lambda x : self.data.tic.values[x], inplace= True)
            df_actions.set_index = df_date  
            #df_actions = pd.DataFrame({'date':date_list,'actions':action_list})
        else:
            date_list = self.date_memory[:-1]
            action_list = self.actions_memory
            df_actions = pd.DataFrame({'date':date_list,'actions':action_list})
        return df_actions

**Comment by Petcron** [comment]
Thanks for giving it a go. I switched the code out and replaced with the version above.
From the Trade section:
trade = data_split(processed_full, '2019-01-01','2021-01-01')
e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 380, **env_kwargs)
# env_trade, obs_trade = e_trade_gym.get_sb_env()

df_account_value, df_actions = DRLAgent.DRL_prediction(
    model=model_sac, 
    environment = e_trade_gym)

I still get the below error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-57-3dbe4275e00b> in <module>
      5 df_account_value, df_actions = DRLAgent.DRL_prediction(
      6     model=model_sac,
----> 7     environment = e_trade_gym)

D:\anaconda3\envs\p36RL\lib\site-packages\finrl\model\models.py in DRL_prediction(model, environment)
     79             account_memory = test_env.env_method(method_name="save_asset_memory")
     80             actions_memory = test_env.env_method(method_name="save_action_memory")
---> 81             test_obs, rewards, dones, info = test_env.step(action)
     82             if dones[0]:
     83                 print("hit end!")

D:\anaconda3\envs\p36RL\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py in step(self, actions)
    148         """
    149         self.step_async(actions)
--> 150         return self.step_wait()
    151 
    152     def get_images(self) -> Sequence[np.ndarray]:

D:\anaconda3\envs\p36RL\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py in step_wait(self)
     42         for env_idx in range(self.num_envs):
     43             obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
---> 44                 self.actions[env_idx]
     45             )
     46             if self.buf_dones[env_idx]:

D:\anaconda3\envs\p36RL\lib\site-packages\finrl\env\env_stocktrading.py in step(self, actions)
    247             self.data = self.df.loc[self.day,:]
    248             if self.turbulence_threshold is not None:
--> 249                 self.turbulence = self.data['turbulence'].values[0]
    250             self.state =  self._update_state()
    251 

AttributeError: 'numpy.float64' object has no attribute 'values'

I'll mess around with it a little more later this eve.

**Comment by Youbadawy** [comment]
@Tarun-Khilani So i tested out the solution, it did not solve it and instead of the initial error it gave me the following

`
ValueError: Length mismatch: Expected axis has 0 elements, new values have 30 elements`

now the issue is not with the date column, its with the actions list, since it is the one that is empty and we are trying to assign an index of 1 to an empty dataframe!

**Comment by Tarun-Khilani** [comment]
@Petcron I don't know how i am not getting that error for Multiple stock trading (DOW_30_TICK with SAC) but when I tried Ensemble I got that error and I will work on it as well

**Comment by Petcron** [comment]
Too good thank you.

**Comment by Tarun-Khilani** [comment]
@Petcron Try removing the .values[0] from line 249 in env in this way
```
self.turbulence = self.data['turbulence']
```

**Comment by alouisos** [comment]
Has anyone solved this? I am getting the same error. Trying from docker container. It seems to be a pandas issue when there is a mismatch of shape between an existing dataframe and trying to add data with different shape

**Comment by Youbadawy** [comment]
@alouisos, if we are discussing the first problem, @Tarun-Khilani's solution had solved it, 

which code are you having @alouisos

**Comment by xjdbie96** [comment]
> Thanks for giving it a go. I switched the code out and replaced with the version above.
> From the Trade section:
> trade = data_split(processed_full, '2019-01-01','2021-01-01')
> e_trade_gym = StockTradingEnv(df = trade, turbulence_threshold = 380, **env_kwargs)
> 
> # env_trade, obs_trade = e_trade_gym.get_sb_env()
> df_account_value, df_actions = DRLAgent.DRL_prediction(
> model=model_sac,
> environment = e_trade_gym)
> 
> ## I still get the below error:
> AttributeError Traceback (most recent call last)
> in
> 5 df_account_value, df_actions = DRLAgent.DRL_prediction(
> 6 model=model_sac,
> ----> 7 environment = e_trade_gym)
> 
> D:\anaconda3\envs\p36RL\lib\site-packages\finrl\model\models.py in DRL_prediction(model, environment)
> 79 account_memory = test_env.env_method(method_name="save_asset_memory")
> 80 actions_memory = test_env.env_method(method_name="save_action_memory")
> ---> 81 test_obs, rewards, dones, info = test_env.step(action)
> 82 if dones[0]:
> 83 print("hit end!")
> 
> D:\anaconda3\envs\p36RL\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py in step(self, actions)
> 148 """
> 149 self.step_async(actions)
> --> 150 return self.step_wait()
> 151
> 152 def get_images(self) -> Sequence[np.ndarray]:
> 
> D:\anaconda3\envs\p36RL\lib\site-packages\stable_baselines3\common\vec_env\dummy_vec_env.py in step_wait(self)
> 42 for env_idx in range(self.num_envs):
> 43 obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
> ---> 44 self.actions[env_idx]
> 45 )
> 46 if self.buf_dones[env_idx]:
> 
> D:\anaconda3\envs\p36RL\lib\site-packages\finrl\env\env_stocktrading.py in step(self, actions)
> 247 self.data = self.df.loc[self.day,:]
> 248 if self.turbulence_threshold is not None:
> --> 249 self.turbulence = self.data['turbulence'].values[0]
> 250 self.state = self._update_state()
> 251
> 
> AttributeError: 'numpy.float64' object has no attribute 'values'
> 
> I'll mess around with it a little more later this eve.

did you solve the error?please lend me a hand

**Comment by Tarun-Khilani** [comment]
@alouisos REplace the function definition of save_action_memory with the one I mentioned above and @xjdbie96  Replace line 249 of the env with this
```
self.turbulence = self.data['turbulence'].iloc[0] 
```
Not sure this if is perfectly correct way.

**Comment by alouisos** [comment]
@Tarun-Khilani thanks for your answer. I spent hours yesterday debugging. Then I found out that the trade part of the RL runs in terminal (in docker) but not in the jupyter notebook (gives me the expected axis error). Never seen that before as a bug. Definitely a Schroedinger bug. Regardless, I can run it in the terminal so I think we are good
