### ISSUE TITLE
Model using current day's data to trade?

### ISSUE THREAD

**Issue by acertainKnight** [AI4Finance-LLC/FinRL-Library#104]
This may not be an issue but I am looking for clarification. I have been going through the code and it seems that the algorithm is purchasing at the open price on day T_0 and being rewarded for the change in price at sale (T_n). As best I can tell, in order to make the decision of buy and sell the algorithm is using data generated on T_0 and T_n. Is this correct? It would seem that the agent should only have information generated up till day T_-1 and T_n-1. Given that the data is daily (not intradaily) it would seem that the agent should need to make decisions based only on information up until the decision day and then should be rewarded based on that same information as though the trading occurs exactly at market open. Am I misunderstanding the code set up?

**Comment by XiaoYangLiu-FinRL** [comment]
Your understanding is far from the practical case.
