### ISSUE TITLE
cannot copy sequence with size 292 to array axis with dimension 301

### ISSUE THREAD

**Issue by mvikasreddy09** [AI4Finance-LLC/FinRL-Library#108]
Hi,

I am getting the bellow error when trying to train the model. I used docker and also custom installation to run this.

Traceback (most recent call last):
  File "main.py", line 53, in <module>
    main()
  File "main.py", line 38, in main
    finrl.autotrain.training.train_one()
  File "/home/finrl/autotrain/training.py", line 76, in train_one
    env_train, _ = e_train_gym.get_sb_env()
  File "/home/finrl/env/env_stocktrading.py", line 379, in get_sb_env
    obs = e.reset()
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 62, in reset
    self._save_obs(env_idx, obs)
  File "/opt/conda/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 92, in _save_obs
    self.buf_obs[key][env_idx] = obs
ValueError: cannot copy sequence with size 292 to array axis with dimension 301

**Comment by Tarun-Khilani** [comment]
Yes I am facing the same issue as well for DOW_30_TICKER

**Comment by limiaobo** [comment]
I guess some value of the tickers is NaN during 2009~2019

**Comment by Tarun-Khilani** [comment]
> I guess some value of the tickers is NaN during 2009~2019, check TESLA and FACEBOOK

Tesla and Facebook are not in DOW_30 list

**Comment by mvikasreddy09** [comment]
Yes its working now. I used Tesla

**Comment by CodingWookie** [comment]
I am having the same issue, not exactly sure what I need to to do.

I am looking at the config.py file and I see that TSLA and FB are not in the DOW_30....  Where is my issue?

**Comment by dumbretard69** [comment]
I have the same problem, I also don't have TSLA and FB. Used other index tickers with similar results.
@mvikasreddy09 How could you make it work?

**Comment by Soumadip-Saha** [comment]
I am also facing the same problem for NIFTY_50 ticks. Did anyone got any solution?
