### ISSUE TITLE
Time Series Reshaping is needed 

### ISSUE THREAD

**Issue by c0x65o** [AI4Finance-LLC/FinRL-Library#12]
It seems your code does not take into consideration stocks with different shapes due to time on market, etc. 

For example, if you use a start date of 2009 and include Facebook ($FB) it will error because Facebook didn't start trading in 2009.

**Comment by hust512** [comment]
Thanks for this issue. Yes, currently, the programmer should pay attention to this and make sure that the historical dataset is complete.  We will address this issue later, or would you like to crack on it?

**Comment by hust512** [comment]
Would you like to join the slack channel for more discussions?

**Comment by hust512** [comment]
"Adding zeros at the beginning of a time series to make the target length"  would be a solution.
