### ISSUE TITLE
some doubts of state

### ISSUE THREAD

**Issue by xjdbie96** [AI4Finance-LLC/FinRL-Library#123]
```
 def _initiate_state(self):
        if self.initial:
            # For Initial State
            if len(self.df.tic.unique()) > 1:
                # for multiple stock
                state = [self.initial_amount] + \
                        self.data.close.values.tolist() + \
                        [0] * self.stock_dim + \
                        sum([self.data[tech].values.tolist() for tech in self.tech_indicator_list], [])
            else:
                # for single stock
                state = [self.initial_amount] + \
                        [self.data.close] + \
                        [0] * self.stock_dim + \
                        sum([[self.data[tech]] for tech in self.tech_indicator_list], [])
        else:
            # Using Previous State
            if len(self.df.tic.unique()) > 1:
                # for multiple stock
                state = [self.previous_state[0]] + \
                        self.data.close.values.tolist() + \
                        self.previous_state[(self.stock_dim + 1):(self.stock_dim * 2 + 1)] + \
                        sum([self.data[tech].values.tolist() for tech in self.tech_indicator_list], [])
            else:
                # for single stock
                state = [self.previous_state[0]] + \
                        [self.data.close] + \
                        self.previous_state[(self.stock_dim + 1):(self.stock_dim * 2 + 1)] + \
                        sum([[self.data[tech]] for tech in self.tech_indicator_list], [])
        return state
```
the above  is initiate state ,initiate_state[(self.stock_dim + 1):(self.stock_dim * 2 + 1)] is 0.
but when we update state:

```
def _update_state(self):
        if len(self.df.tic.unique()) > 1:
            # for multiple stock
            state = [self.state[0]] + \
                    self.data.close.values.tolist() + \
                    list(self.state[(self.stock_dim + 1):(self.stock_dim * 2 + 1)]) + \
                    sum([self.data[tech].values.tolist() for tech in self.tech_indicator_list], [])

        else:
            # for single stock
            state = [self.state[0]] + \
                    [self.data.close] + \
                    list(self.state[(self.stock_dim + 1):(self.stock_dim * 2 + 1)]) + \
                    sum([[self.data[tech]] for tech in self.tech_indicator_list], [])
```

so the next state values of index from self.stock_dim + 1 to self.stock_dim * 2 + 1 will use previous state[(self.stock_dim + 1):(self.stock_dim * 2 + 1)] which is also 0.
so state values in index from self.stock_dim + 1 to self.stock_dim * 2 + 1  is always 0.
so in fact we could delete these values of state? @louisowen6

**Comment by louisowen6** [comment]
Hi, thanks for your question. 

Actually, the 'self.stock_dim + 1 to self.stock_dim * 2 + 1' index of state (or simply called our asset's holdings) is not always 0, since it's updated when we call the 'step' method.

**Comment by xjdbie96** [comment]
> Hi, thanks for your question.
> 
> Actually, the `self.stock_dim + 1 to self.stock_dim * 2 + 1` index of state (or simply called our asset's holdings) is not always 0, since it's updated when we call the `step` method.

thank you for reply. and I have another question while making transaction.Can the agent make short selling?Or It only can  sell stock when we have brought some stock  before and it can't sell stock more than we hold?

**Comment by louisowen6** [comment]
> > Hi, thanks for your question.
> 
> > 
> 
> > Actually, the `self.stock_dim + 1 to self.stock_dim * 2 + 1` index of state (or simply called our asset's holdings) is not always 0, since it's updated when we call the `step` method.
> 
> 
> 
> thank you for reply. and I have another question while making transaction.Can the agent make short selling?Or It only can  sell stock when we have brought some stock  before and it can't sell stock more than we hold?

Hi, currently it still can't handle short-selling strategy. Feel free to contribute your own env to accompdate this needs :)
