### ISSUE TITLE
New Commits Break Training

### ISSUE THREAD

**Issue by svuhoang** [AI4Finance-LLC/FinRL-Library#13]
The new commits using stable-baselines-3 broke the training. When I train the agent in the single stock trading jupyter notebooks, it prints the following while it trains: 
begin_total_asset:100000
end_total_asset:100000.0
total_reward:0.0
total_cost:  0
total_trades:  0

**Comment by hust512** [comment]
We are looking into this. Thx.    Would be good if you can join the slack channel (at the top of the readme file) for more discussions.

**Comment by BruceYanghy** [comment]
> The new commits using stable-baselines-3 broke the training. When I train the agent in the single stock trading jupyter notebooks, it prints the following while it trains:
> begin_total_asset:100000
> end_total_asset:100000.0
> total_reward:0.0
> total_cost: 0
> total_trades: 0

This TD3 model, right? I fixed it, the parameters from stable-baselines2 to stable-baselines3 is pretty different. Please try again.

Those hyperparameters are not tailored for stock trading nor Finance. Need to tune all the time.

**Comment by ariesvtb** [comment]
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pandas/core/series.py in wrapper(self)
    128             return converter(self.iloc[0])
--> 129         raise TypeError(f"cannot convert the series to {converter}")
    130 

TypeError: cannot convert the series to <class 'float'>


Error I get when running A2C model in example notebook

**Comment by hust512** [comment]
Updated. Would you please have another try?
