### ISSUE TITLE
Docker installation does not work in computers without GPU 

### ISSUE THREAD

**Issue by merlos** [AI4Finance-LLC/FinRL-Library#132]
To install the docker 

I changed the first line of `docker/Dockerfile` to:

```
FROM stablebaselines/rl-baselines3-zoo-cpu
```

And it worked. 

It would be nice to have a Dockerfile for non GPU.

**Comment by spencerR1992** [comment]
Could you please add a new dockerfile and script to support this functionality? This is a welcomed contribution!
