### ISSUE TITLE
Import errors in notebooks

### ISSUE THREAD

**Issue by merlos** [AI4Finance-LLC/FinRL-Library#134]
From a fresh clone of the library. Some imports in notebooks fail.

**FinRL_ensemble_stock_trading_ICAIF_2020.ipynb**
![image](https://user-images.githubusercontent.com/404446/107868790-1ba4e900-6e55-11eb-96dc-a18a5f8595bd.png)

**notebooks/multistock_docker.ipynb**
![image](https://user-images.githubusercontent.com/404446/107868737-ba7d1580-6e54-11eb-913c-f6fdc2ab6023.png)

I haven't checked all, but similar issues may exist in others.

BTW, thanks for the library.

**Comment by BruceYanghy** [comment]
It's fixed please try again from the FinRL-Library folder. Thanks.

**Comment by RajS999** [comment]
> It's fixed please try again from the FinRL-Library folder. Thanks.

the v2 files is not there in [this](https://github.com/AI4Finance-LLC/FinRL-Library/tree/master/finrl/env) folder right?
