### ISSUE TITLE
use btc data ,but get error

### ISSUE THREAD

**Issue by wac81** [AI4Finance-LLC/FinRL-Library#14]
get error
`ValueError: setting an array element with a sequence.`

i  locate error in /home/xxx/.local/lib/python3.6/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py:
```
            obs, self.buf_rews[env_idx], self.buf_dones[env_idx], self.buf_infos[env_idx] = self.envs[env_idx].step(
                self.actions[env_idx]
            )
```
self.buf_rews[env_idx] length not equal self.envs[env_idx].step(self.actions[env_idx])[1]

i get self.envs[env_idx].step(self.actions[env_idx])[1] = `[0. 0. 0. 0.]`

but self.buf_rews[env_idx] origin value = `<class 'tuple'>: (0.0,)`

and data difference is date = `’2020-12-19 12:00:00‘`,   and is no tic , then I fill in BTC or AAPL

**Comment by JackWBoynton** [comment]
I got it working with both hourly and daily here: [https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_day.csv](https://www.cryptodatadownload.com/cdd/gemini_BTCUSD_day.csv) without this error. I would double-check that your state space and action spaces are correct throughout the step of your environment.

**Comment by wac81** [comment]
sorry, it's my fault, my data has duplicate

**Comment by hust512** [comment]
Your may join our slack channel for btc discussions.
