### ISSUE TITLE
Sharpe Ratio Validity

### ISSUE THREAD

**Issue by ava6969** [AI4Finance-LLC/FinRL-Library#15]
Why do we use 252 for the sharpe ratio calculation at the end of an episode. Looks like we using portfolio change from the beginning of the file which will be 9 years of trading period. so shouldn't 252 be replaced with self.days.

**Comment by BruceYanghy** [comment]
> sharpe ratio

It's annualize Sharpe Ratio. Calculating the Sharpe ratio using daily returns: the average of the daily returns is divided by the sampled standard deviation of the daily returns and that result is multiplied by the square root of 252–the typical number of trading days per year in the USA markets.

Also, in real life trading, you should use portfolio’s excess return = return of the portfolio - risk free rate

**Comment by ava6969** [comment]
Thank you very much, do you have any idea on how i could use this formula for minute data sets. should i still leave this as is

**Comment by JackWBoynton** [comment]
There will be a lot more volatility if using just intraday sharpe ratios, therefore in my opinion it would be best to leave as is.
