### ISSUE TITLE
Problem of multi_stock_trading float division by zero

### ISSUE THREAD

**Issue by Mostafasaeed29** [AI4Finance-LLC/FinRL-Library#151]
This is the code i have,
tensorboard --logdir ./multiple_stock_tensorboard/
add noise to the action in DDPG helps in learning for better exploration
n_actions = env_train.action_space.shape[-1]
param_noise = None
action_noise = OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=float(0.5) * np.ones(n_actions))
------------------------------------------------------------------------------------------------------------------------------
And this is the error.
model settings
model_ddpg = DDPG('MlpPolicy', 
                   env_train,
                   batch_size=64,
                   buffer_size=100000,
                   param_noise=param_noise, 
                   action_noise=action_noise,
                   verbose=0, 
                   tensorboard_log="./multiple_stock_tensorboard/")

250k timesteps: took about 20 mins to finish
model_ddpg.learn(total_timesteps=250000, tb_log_name="DDPG_run_1")

<ipython-input-38-8abf50d2ba70> in step(self, actions)
    108             df_total_value['daily_return']=df_total_value.pct_change(1)
    109             sharpe = (252**0.5)*df_total_value['daily_return'].mean()/ \
--> 110                   df_total_value['daily_return'].std()
    111             print("Sharpe: ",sharpe)
    112             print("=================================")

ZeroDivisionError: float division by zero

-------------------------------------------------------------------------------------------
So, anyone can help?
Thanks in advance.

**Comment by Tarun-Khilani** [comment]
was your model learning? because the daily return value must be zero if this error is there.

**Comment by Mostafasaeed29** [comment]
Yes thanks i have solved it!
But got another comment , what is the best way to get better alpha number (Techincal indicators and learning rate) , or its just try and error.

**Comment by Tarun-Khilani** [comment]
Yes it is kind of trial and error but if you observe logs you can get an idea

**Comment by SamCurtis111** [comment]
@Mostafasaeed29  what did you do to fix this? I have encountered the same problem and am not sure what has caused the issue
