### ISSUE TITLE
Note book not found 

### ISSUE THREAD

**Issue by phamanhtu17295** [AI4Finance-LLC/FinRL-Library#154]
Can I have access to these notes book?
https://colab.research.google.com/github/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_single_stock_trading.ipynb
https://colab.research.google.com/github/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_multiple_stock_trading.ipynb
https://colab.research.google.com/github/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_portfolio_allocation.ipynb

Thank you very much for your consideration.

**Comment by phamanhtu17295** [comment]
Traceback (most recent call last):
  File "/home/polly/Desktop/code/Qlib test/fin rl testing.py", line 9, in <module>
    from finrl.config import config
  File "/home/polly/anaconda3/envs/findatapy/lib/python3.7/site-packages/finrl/config/config.py", line 1244, in <module>
    "IFX.DE"
NameError: name 'config' is not defined
 
I also run into this problem when trying to run portfolio allocation.

**Comment by BruceYanghy** [comment]
It's fixed please try again from the FinRL-Library folder. Thanks.

**Comment by phamanhtu17295** [comment]
> It's fixed please try again from the FinRL-Library folder. Thanks.

![Screenshot from 2021-02-26 09-06-43](https://user-images.githubusercontent.com/74130487/109244990-465a4e80-7812-11eb-958a-148fb1b5a242.png)

**Comment by BruceYanghy** [comment]
Please update the repository.
