### ISSUE TITLE
Question: Include fundamental data

### ISSUE THREAD

**Issue by M-Colley** [AI4Finance-LLC/FinRL-Library#159]
Hey, I was wondering whether one could include fundamental data into the trading? Currently, I only see the TECHNICAL_INDICATOR_LIST, but I was wondering whether I could "misuse" this also for fundamental data or whether this project could also provide a FUNDAMENTAL_INDICATOR_LIST. Any thoughts on this?

Kind regards

**Comment by XiaoYangLiu-FinRL** [comment]
The algorithms allows versatile choices of indicators as states, and also reward functions. The performance depends on the test of specific tasks.

**Comment by M-Colley** [comment]
To be specific, I could add a column "net_income" which would only change per year, and add this to the TECHNICAL_INDICATOR_LIST, and this would work with SAC, for example?

**Comment by XiaoYangLiu-FinRL** [comment]
Sure, It should work.
