### ISSUE TITLE
Turbulence Index

### ISSUE THREAD

**Issue by niveshigovind** [AI4Finance-LLC/FinRL-Library#16]
A better way to use turbulence Index is to apply Mahalanobis Dist.. on returns timeseries rather than the levels as you are doing...

**Comment by BruceYanghy** [comment]
> Mahalanobis Dist

That's a great idea! Please join our open-source community:

 https://join.slack.com/t/ai4financeworkspace/shared_invite/zt-jyaottie-hHqU6TdvuhMHHAMXaLw_~w
