### ISSUE TITLE
ImportError: cannot import name 'BackTestStats' from 'finrl.trade.backtest' (/Users/maa/projects/finRL/FinRL-Library/finrl/trade/backtest.py)

### ISSUE THREAD

**Issue by mardaasik** [AI4Finance-LLC/FinRL-Library#165]
I get the following error when I try to run any code, including main.py

ImportError: cannot import name 'BackTestStats' from 'finrl.trade.backtest' (/Users/maa/projects/finRL/FinRL-Library/finrl/trade/backtest.py)

I have python 3.7 and installed Pyfolio.

**Comment by setar** [comment]
try backtest_stats

from finrl.trade.backtest import backtest_stats, backtest_plot, get_daily_return, get_baseline

**Comment by mardaasik** [comment]
The error is inside package files, particularly it happens when I run "import finrl.autotrain.training".

It tries "from finrl.trade.backtest import BackTestStats". This is where the error is.

**Comment by spencerR1992** [comment]
That module has been changed. Please pull the latest code and read the new implementation!
