### ISSUE TITLE
Traditional trading strategies

### ISSUE THREAD

**Issue by diffunity** [AI4Finance-LLC/FinRL-Library#174]
Hi! I am trying to use FinRL-Library for some research purposes. I have read your paper published in NIPS 2020. In 4.2 Baseline Trading Strategies, I read that "FinRL uses five conventional strategies". So far, I was only able to find the buy-and-hold strategy in finrl > tools > trade.py 

Are they somewhere else in this repository? or are they still being implemented? Thank you!

**Comment by XiaoYangLiu-FinRL** [comment]
Check out other repos please. In FinRL, we focus on RL. The FinRL project is not for one-paper purpose, and is open source platform. Others are well established in our previous projects.  Let me know if you have troubles.
