### ISSUE TITLE
ModuleNotFoundError: No module named 'finrl.env.environment'  error

### ISSUE THREAD

**Issue by xanstorm** [AI4Finance-LLC/FinRL-Library#176]
I got this error that another person got. I installed feature engine. What am I doing wrong? Thanks for the assist.
![Screen Shot 2021-03-12 at 2 57 34 PM](https://user-images.githubusercontent.com/7649650/110991977-4ba3b700-8343-11eb-958a-acebc5dfd298.jpg)

**Comment by xanstorm** [comment]
Please close. I have a separate issue unrelated to this. I fixed this error. Thnx

**Comment by BruceYanghy** [comment]
Cool, we removed environment.py, everything is included in the env file for example: from finrl.env.env_stocktrading import StockTradingEnv

**Comment by xanstorm** [comment]
Hi Bruce,
Can I bug you again?
I get this error and can't get past it. What am I doing wrong?
Thanks a lot.
Stephen
[image: Screen Shot 2021-03-14 at 2.07.30 PM.jpg]

Stephen Hobbs, M.Sc., MBA
Skype: stephenmhobbs
Cell: 404-441-2858
