### ISSUE TITLE
CAC40 AttributeError: 'numpy.ndarray' object has no attribute 'values'

### ISSUE THREAD

**Issue by Timodhau** [AI4Finance-LLC/FinRL-Library#178]
Hi,

I am having an issue in trying to train the model with CAC_40_TICKER in FInRL_portfolio_allocation_NeurIPS_2020.ipynb

<ipython-input-22-4cd1ee1367f4> in step(self, actions)
    156             self.day += 1
    157             self.data = self.df.loc[self.day,:]
--> 158             self.covs = self.data['cov_list'].values[0]
    159             self.state =  np.append(np.array(self.covs), [self.data[tech].values.tolist() for tech in self.tech_indicator_list ], axis=0)
    160             #print(self.state)

AttributeError: 'numpy.ndarray' object has no attribute 'values'

**Comment by meng-x** [comment]
a possible work around.
open the corresponding file and uncomment ".values[0]", save, and restart the notobook environment(if you are using colab)

* remember the file and line number that altered.

**Comment by Timodhau** [comment]
uncomment ? I did not found .values[0] to uncomment, if you mean comment it lead me to a shape error.

**Comment by Timodhau** [comment]
it looks like my cov_list hasnt the same shape on all rows, haveing some users warning when i add covariance matrix as states:
C:\Users\timod\Anaconda3\envs\rl\lib\site-packages\numpy\lib\function_base.py:380: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis)
C:\Users\timod\Anaconda3\envs\rl\lib\site-packages\numpy\core\_methods.py:181: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
C:\Users\timod\Anaconda3\envs\rl\lib\site-packages\pandas\core\frame.py:8525: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
C:\Users\timod\Anaconda3\envs\rl\lib\site-packages\numpy\lib\function_base.py:2493: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
C:\Users\timod\Anaconda3\envs\rl\lib\site-packages\numpy\lib\function_base.py:2493: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
C:\Users\timod\Anaconda3\envs\rl\lib\site-packages\pandas\core\frame.py:8525: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
