### ISSUE TITLE
FinRL_multiple_stock_trading - ValueError: operands could not be broadcast together with shapes (30,) (0,) 

### ISSUE THREAD

**Issue by harshadvekariya** [AI4Finance-LLC/FinRL-Library#18]
I am trying to run the code provided for FinRL_multiple_stock_trading, but I get Value error while running the following line. 

```
df_account_value, df_actions = DRLAgent.DRL_prediction(model=model_sac,
                        test_data = trade,
                        test_env = env_trade,
                        test_obs = obs_trade)

```
@BruceYanghy Can you please tell how it can be solved? Thank you very much for sharing your work, I would like to experiment with your code, appreciate your help.

Best,
Harshad

**Comment by holycraftcanada** [comment]
I got this when running under v3.8, but worked fine using v3.7

**Comment by szation** [comment]
I am having the same issue when running on Colab.
Python version is 3.6.9

**Comment by tedircks** [comment]
I had this issue as well but saw that @BruceYanghy made an update to `EnvMultipleStock_trade.py` which fixed the issue. Replacing the total reward print statement on lines 134-135 with the following code fixes the error. I'm still investigating why this works, but it is worth noting that the change was reverted in a later commit.

`print("total_reward:{}".format(self.state[0]+sum(np.array(self.state[1:(self.stock_dim+1)])
                                                             * np.array(self.state[(self.stock_dim+1):61])) - self.asset_memory[0]))`

**Comment by BruceYanghy** [comment]
61 is hardcoded, I changed it to (self.stock_dim*2+1)
