### ISSUE TITLE
How to save and load the trained model?

### ISSUE THREAD

**Issue by zhangzhenslamdunk** [AI4Finance-LLC/FinRL-Library#182]
How to save and load the trained model?

**Comment by venellinus1** [comment]
for saving you can do(assuming model name is 'model'): 
model.save("somename.model")
or if model name is eg model_ppo then:
model_ppo.save("somename.model")

for loading the model (assuming its uploaded to your notebook  ):
model_ppo=model_ppo.load("somename.model")
