### ISSUE TITLE
Indicator_df is not matching is not matching dataframe indexes.

### ISSUE THREAD

**Issue by NoahSfi** [AI4Finance-LLC/FinRL-Library#186]
Hi,

When working on multi assets, we first sort the dataframe by date and then add indicators. The issue is that we calculate those indicators assets by assets and then add this column to the original dataframe. So we have something like that:
1- First dataset : GOOGL/AAPL/GOOGL/AAPL/.....GOOGL/AAPL/
2- Indicator columns: GOOGL/GOOGL/GOOGL/GOOGL/...../AAPL/AAPL/AAPL/AAPL

**Comment by XiaoYangLiu-FinRL** [comment]
I believe this issue is fixed after several rounds of interaction. Great job!
