### ISSUE TITLE
What's the correct way to interpret the results

### ISSUE THREAD

**Issue by holycraftcanada** [AI4Finance-LLC/FinRL-Library#19]
is the actions means trading action for next trading day? 

if the results has the following values (using APPL as an example)- 

- date: 2020-12-01
- actions: [200]
- close_price: 122.72

Does this mean the trading action for Dec. 2nd is to buy 100 APPL? Trying to understand how we can use the results from the models.

thanks

**Comment by JackWBoynton** [comment]
See section 5, here: [https://github.com/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_single_stock_trading.ipynb](url) where it explains the environment setup.

**Comment by BruceYanghy** [comment]
> is the actions means trading action for next trading day?
> 
> if the results has the following values (using APPL as an example)-
> 
> * date: 2020-12-01
> * actions: [200]
> * close_price: 122.72
> 
> Does this mean the trading action for Dec. 2nd is to buy 100 APPL? Trying to understand how we can use the results from the models.
> 
> thanks

https://towardsdatascience.com/finrl-for-quantitative-finance-tutorial-for-multiple-stock-trading-7b00763b7530

Please refer to this blog, we explained all the steps and results, also provided a made-up example.
