### ISSUE TITLE
Missing Learning Rate for DDPG in Multiple Stock/ Portfolio Trading

### ISSUE THREAD

**Issue by GregSavic** [AI4Finance-LLC/FinRL-Library#24]
KeyError                                  Traceback (most recent call last)
<ipython-input-22-e4e07db887a6> in <module>()
      6                                        'verbose':0,
      7 			               'timesteps':50000}
----> 8 model_ddpg = agent.train_DDPG(model_name = "DDPG_{}".format(now), model_params = ddpg_params_tuning)

/usr/local/lib/python3.6/dist-packages/finrl/model/models.py in train_DDPG(self, model_name, policy, model_params, policy_kwargs)
     82                     batch_size=model_params['batch_size'],
     83                     buffer_size=model_params['buffer_size'],
---> 84                     learning_rate=model_params['learning_rate'],
     85                     action_noise=action_noise,
     86                     verbose=model_params['verbose'],

KeyError: 'learning_rate'

**Comment by BruceYanghy** [comment]
I just updated the jupyter notebook for multiple stocks and portfolio allocation, please try again. Thanks.
