### ISSUE TITLE
Refactor FeatureEngineer to accept df in preprocess_data()

### ISSUE THREAD

**Issue by spencerR1992** [AI4Finance-LLC/FinRL-Library#25]
Implementing the class without the DF parameter will allow this to be re-used in other contexts without being re-initialized. 
This could be useful in designing backtesting.

**Comment by hust512** [comment]
Not understand. But you can try and pull a request, we are happy to include such a feature/function.

**Comment by BruceYanghy** [comment]
> Implementing the class without the DF parameter will allow this to be re-used in other contexts without being re-initialized.
> This could be useful in designing backtesting.

Thank you so much!! Did you join our slack open community?

https://join.slack.com/t/ai4financeworkspace/shared_invite/zt-jyaottie-hHqU6TdvuhMHHAMXaLw_~w

**Comment by BruceYanghy** [comment]
> Implementing the class without the DF parameter will allow this to be re-used in other contexts without being re-initialized.
> This could be useful in designing backtesting.

Maybe you can join us for our academic research papers in 2021. Our current focus is ICAIF 2021 (target 5 articles) and NeurIPS (Deep RL workshop), I am responsible for at least 2 articles for each conference. FinRL is our DRL framework, we can always refer back to this repo to do the coding for our new papers, we have some research initiatives in our mind for ICAIF 2021:

Research Initiatives:
- Portfolio Allocation using DRL;
- High-frequency trading using DRL;
- Cryptocurrency trading using DRL;
- DRL v.s. Human trader;
- Live trading using DRL;
- Application of RL to Financial Arbitrage;
- Explainable DRL in Finance;
- Quantum RL in finance;
- Multi-Agent RL in Finance;
- Closing the simulation-reality gap of DRL in Finance;
- SOTA DRL for Finance (checking RLZoo);
- Benchmarking DRL performance in Finance;
- Lightweight DRL in Finance;
- Sequential RL in Finance;
- inverse reinforcement learning in Finance;
- Hamiltonian reinforcement learning in finance;
- Hamilton-Jacobi-Bellman Equations for continuous RL in finance;
- Mean Field Multi-Agent Reinforcement Learning in finance;
