### ISSUE TITLE
where is DQN?

### ISSUE THREAD

**Issue by xjdbie96** [AI4Finance-LLC/FinRL-Library#27]
this project include DQN, DDPG, PPO, SAC, A2C, TD3, etc.I want to do some reach in DQN.whre is the DQN model scipts.if I want to train a DQN.what parameter should I pass.

**Comment by Bturan19** [comment]
@xjdbie96 I'm not a contributor but; /finrl/model.py. You should look at that script. You can pass your parameters there. Models are actually comes from "stable_baseline3".

**Comment by xjdbie96** [comment]
> @xjdbie96 I'm not a contributor but; /finrl/model.py. You should look at that script. You can pass your parameters there. Models are actually comes from "stable_baseline3".

thank you for reply.I have found this from stable_baseline3. Actually ,I want to find the action space script for all the RL algorithm. And I not sure this project action space or stock position is [-1,0,1].I want to define stock position as [0,1].Also ,I want to improve the reward function.

**Comment by hust512** [comment]
Please joint the clack channel for discussing detailed parameter settings.

**Comment by xjdbie96** [comment]
> Please joint the clack channel for discussing detailed parameter settings.



> Please joint the clack channel for discussing detailed parameter settings.

Again  ,thank you  for  reply .I am a new guy for github .how to  join this channel ?.looking  forward to your reply

**Comment by hust512** [comment]
Try this link: https://app.slack.com/client/T01GYDU6KB6/D01GL7D8N94

**Comment by xjdbie96** [comment]
> Try this link: https://app.slack.com/client/T01GYDU6KB6/D01GL7D8N94
Awesome !Thank you very  much . Pretty noce guys !
