### ISSUE TITLE
FinRL_multiple_stock_trading FIX "now" problem

### ISSUE THREAD

**Issue by TekpreXyz** [AI4Finance-LLC/FinRL-Library#36]
print("==============Get Backtest Results===========")

now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M') **<--------------please add this line**

perf_stats_all = BackTestStats(account_value=df_account_value)
perf_stats_all = pd.DataFrame(perf_stats_all)
perf_stats_all.to_csv("./"+config.RESULTS_DIR+"/perf_stats_all_"+now+'.csv')

![image](https://user-images.githubusercontent.com/73416709/103486355-84805680-4dfd-11eb-9d66-36059816d7f4.png)

**Comment by BruceYanghy** [comment]
Fixed. thanks
