### ISSUE TITLE
Formatting own dataset 

### ISSUE THREAD

**Issue by zyzhang1130** [AI4Finance-LLC/FinRL-Library#37]
Hi, can anyone kindly point out if there is a guide on how to make one's own data into the same format as the example dataset? I tried to simply import csv of my own data but there are a couple of attributes missing when I initialize the environment. For example, if I want to use intraday data or tick data how should I format my 'date' attribute? Thanks a lot

**Comment by TekpreXyz** [comment]
this is python fundamental knowledge problem, it has nothing to do with the library, try to study the pandas module
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

**Comment by zyzhang1130** [comment]
Thanks for those recourses, I think it is still somewhat relevant because in the way I would like to know that kind of format for the data the library can recognize (e.g. is that the library can only take in OHLC format?)

**Comment by TekpreXyz** [comment]
there are many formats; to my knowledge there is no single way to make them usable. Everyone has to create their own translation macro based on the data they want to work on.
Basically any trading library works on a dataframe in which the price refers to a certain time, nothing more than an ordered list.

**Comment by TekpreXyz** [comment]
there are many formats; to my knowledge there is no single way to make them usable. Everyone has to create their own translation macro based on the data they want to work on.
Basically any trading library works on a dataframe in which the price refers to a certain time, nothing more than an ordered list.

**Comment by zyzhang1130** [comment]
Noted with thanks

**Comment by TekpreXyz** [comment]
however keep in mind that the standard ohlc format is necessary if it should be useful to work with indicator libraries such as Ta-lib

**Comment by TekpreXyz** [comment]
for example if you want to use  slowk indicator from talib it's necessari that 'high', 'low', 'open' colum are present in your dataframe
otherwise it will fail
slowk, slowd = STOCH(input_arrays, 5, 3, 0, 3, 0, prices=['high', 'low', 'open'])
but if you only want work whit SMA you only need one price reference 
from talib.abstract import *
output = SMA(input_arrays, timeperiod=25) # calculate on close prices by default
output = SMA(input_arrays, timeperiod=25, price='open') # calculate on opens

**Comment by zyzhang1130** [comment]
Thanks for the supplementary info!
