### ISSUE TITLE
How to train model with my GPU

### ISSUE THREAD

**Issue by dashan0313** [AI4Finance-LLC/FinRL-Library#38]
Hi,
I just want to know how can I train my DRL model with GPU. (to speed up the training process)

Thank you!

**Comment by TekpreXyz** [comment]
not possible

**Comment by BruceYanghy** [comment]
stable-baselines of tf1.14 can support GPU, but we switched to stable-baselines3 with PyTorch, still waiting for the TF 2.0 version.

**Comment by TekpreXyz** [comment]
there are TF 2.4 here
