### ISSUE TITLE
result of trade 

### ISSUE THREAD

**Issue by pwner4810** [AI4Finance-LLC/FinRL-Library#5]
hey sir thanks for your helpful article 
I've read your article in two form ensemble strategy and this model 
with comparison of backtesting result   could you please speak about  why this model  is working better than ensemble strategy  and what improvement are you going  to  implement in the new version of this model

**Comment by BruceYanghy** [comment]
> hey sir thanks for your helpful article
> I've read your article in two form ensemble strategy and this model
> with comparison of backtesting result could you please speak about why this model is working better than ensemble strategy and what improvement are you going to implement in the new version of this model

I have been improving the state-of-the-art (SOTA) performance of the DRL algorithms in stock trading. I wouldn't say that that this model is better than the ensemble strategy. I will incorporate the ensemble strategy into the FinRL library in our next version.

**Comment by saeed48104617** [comment]
oh that's the point ! . thanks a lot just another you have skipped validation process is that a part of improving ? 
 im definitely one of your fan  because of you explanation documentation and of course knowledge 
thanks .

**Comment by BruceYanghy** [comment]
> oh that's the point ! . thanks a lot just another you have skipped validation process is that a part of improving ?
> im definitely one of your fan because of you explanation documentation and of course knowledge
> thanks .

The validation process is just for model selection in ensemble strategy. In real life trading, it's better to have a paper trading stage to test the algorithm.

**Comment by hust512** [comment]
Is this issue fixed, and can be closed?
