### ISSUE TITLE
Observation Stacking

### ISSUE THREAD

**Issue by xiedidan** [AI4Finance-LLC/FinRL-Library#51]
It seems your code doesn't consider time series of observations?
Since there'll be no recurrent policy in stable baselines3 before v1.2, current implementation only takes 1 day's observation into consideration.
Did I miss anything that creates time series implicitly?

**Comment by hust512** [comment]
Yes, we haven't used observations of several time slots, currently it uses 1 day's observation (price, share).  Using LSTM to encode a time series of observations into a latent state is promising.  Do you have some idea that worth a trial?  Thanks.

**Comment by xiedidan** [comment]
I simply stacked 30 days' state, but no better result. Will give LSTM a try, thanks.

**Comment by XiaoYangLiu-FinRL** [comment]
Join the slack channel, can have better discussions.
