### ISSUE TITLE
error in compute turbulence

### ISSUE THREAD

**Issue by wac81** [AI4Finance-LLC/FinRL-Library#53]
found out an error in compute turbulence,
show error:
`LinAlgError: Singular matrix`

The problem arises due to the perfect correlation between the two series in your data

so i fix it use np.linalg.inv -->np.linalg.pinv, but this not best solution.

we can fix it like that, add just a little noise to your data, the error disappears, and still use linalg.inv:
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import grangercausalitytests

n = 1000
ls = np.linspace(0, 2*np.pi, n)
df1Clean = pd.DataFrame(np.sin(ls))
df2Clean = pd.DataFrame(2*np.sin(ls+1))
dfClean = pd.concat([df1Clean, df2Clean], axis=1)
dfDirty = dfClean+0.00001*np.random.rand(n, 2)

grangercausalitytests(dfClean, maxlag=20, verbose=False)    # Raises LinAlgError
grangercausalitytests(dfDirty, maxlag=20, verbose=False)    # Runs fine

```
but i have question?
which is turbulence effect？Is it necessary？Can other calculations be used instead?

**Comment by XiaoYangLiu-FinRL** [comment]
It is not necessary.  Also, would be please test the new env?
You problem may relate with not-equal-length of the stock price data, we have fixed that issue.
