### ISSUE TITLE
realtime data

### ISSUE THREAD

**Issue by err4o4** [AI4Finance-LLC/FinRL-Library#6]
Hey! Thanks for great article and library. Ive trained model on historical data. Is it possible to add data in realtime from websockets for example? And make predictions every time new data comes? 
Thanks

**Comment by err4o4** [comment]
Hi there
I want to make buy/sell/hold action when new data comes. Say me if i understood correctly:

globally:
1. load model: ```model = SAC.load(...)```

on_first_data_received :
1. init:  ```trade_data = pd.DataFrame([...])```
2. setup environment: ```env_setup = EnvSetup(...)```
3. setup trading env: ```env_trade, obs_trade = env_setup.create_env_trading(trade_data)```
4. predict: ```action, _states = model.predict(obs_trade)```
5. act: ```obs_trade, rewards, dones, info = env_trade.step(action)```

on_next_data_received:
1. append new data: ```trade_data.append(new_trade_data)```
2. update env_trade df: ```env_trade.set_attr('df', trade_data)```
3. predict: ```action, _states = model.predict(obs_trade)```
4. act: ```obs_trade, rewards, dones, info = env_trade.step(action)```

**Comment by hust512** [comment]
You are considering to test on real-time, namely support live trading.  Am I right?   In this case, you can simple loaded your trained model and do the trading. The model can be retrained everyday or every few days.
