### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by amihos** [AI4Finance-LLC/FinRL-Library#60]
I am following multi stock notebook. When about to train the first model I got this error message:

Model 1: A2C
agent = DRLAgent(env = env_train)
model_a2c = agent.get_model("a2c")
{'n_steps': 5, 'ent_coef': 0.01, 'learning_rate': 0.0007}
Using cpu device
/opt/conda/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on **your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370116979/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0**
  
 I have a RTX2060 graphic card and the latest driver. What else should I do to be able to use it with the algorithm?

**Comment by carlogrisetti** [comment]
Make sure you have PyTorch installed with the appropriate cuda version (latest supported is 11.0)
You can get the install command here: https://pytorch.org/get-started/locally/
Also, you should install CUDA 11.0

**Comment by amihos** [comment]
Thank you for the help. I installed Cuda. Now I do not get that error
message however the algorithm is still using the CPU. Do you have any idea
how I can force it to use the GPU?
|

**Comment by amihos** [comment]
I could mange to get the algorithm to use cuda device and it says actually that it is using cuda device however when I check task manager it shows that the cpu is being used! Any idea why?

**Comment by carlogrisetti** [comment]
It is *also* using the cpu :)

**Comment by amihos** [comment]
> Es _also_ using the cpu :)

at 100%? while GPU is sitting at 0-1%?

**Comment by amihos** [comment]
I just tried CartPole training algorithm from https://stable-baselines3.readthedocs.io/en/master/guide/examples.html and it clearly uses my GPU constantly at 90% 
so there is something going on with the finrl algorithm

**Comment by carlogrisetti** [comment]
Yes, not all agents can use GPU. Some are more optimized than others, and it depends on the task to do.
Other than that, I can't help you anymore :)

**Comment by amihos** [comment]
Thank you for the explanation. I know now :)

**Comment by XiaoYangLiu-FinRL** [comment]
Our new version will fully support GPUs.

**Comment by niceban** [comment]
> Our new version will fully support GPUs.

Has it released by now? And does it support for DQN and A2C?

**Comment by ashmitsharma** [comment]
@amihos can you please share the code. You modified to use CartPole algorithm.
Thank You
