### ISSUE TITLE
Agent Deployment

### ISSUE THREAD

**Issue by parrondo** [AI4Finance-LLC/FinRL-Library#61]
Hi,

Congrat for this great work. I have a questions: How are you thinking to deploy these agents for paper trading or production (that is with real streaming price)?

Thank you

**Comment by hust512** [comment]
Two ways: 1. save model, and load it for testing;  2. Build a virtual environment with APIs for paper trading, so that it can be tested with streaming in data.  Any thought from your end?  We would like to make it easier to use, also welcome contributions from the community.  Thx.

**Comment by parrondo** [comment]
Well, I was thinking about something more stable and scalable. We must remember that final goal is to place orders in a broker platform.
I am working in a solution based on Ray. Ray Serve's Python API is framework independent and allows you to use the same framework in which you trained your model. Ray Serve runs over Ray which is vendor neutral and has built-in support for deployment on public clouds (AWS, GCP, Azure) and even in Kubernetes, YARN or SLURM, as well as on local machines.

If you are interested in this solution, let me know how I could contribute.

**Comment by hust512** [comment]
Agree that "final goal is to place orders in a broker platform".   Ray RLlib is very good!   In our group, we discussed a lot about it.  And very interested in creating an integrated module for such a support.

**Comment by hust512** [comment]
Based on some previous testings on Ray RLlib, we also believe that Ray RLlib is much faster in training (especially on cloud clusters, we tested it on a few nodes, not tens or hundreds of nodes). Would it be possible to have a solution on cloud: training on a cloud and testing by connecting with finance APIs?   Let me know your thoughts, I believe Ray RLlib is a big one and may need some efforts.  Would you like to join the slack channel and discuss with others too?   Here is the link: https://app.slack.com/client/T01GYDU6KB6/C01KAPTH540

**Comment by parrondo** [comment]
Thank you hust512. Yes I would like to join the slack channel but the link is not working for me. ¿Which is the name of your slack channel?

**Comment by hust512** [comment]
The slack channel is called: AI4FInance
You may it at this top of the readme file:  https://github.com/AI4Finance-LLC/FinRL-Library
