### ISSUE TITLE
google colab not working

### ISSUE THREAD

**Issue by mikelty** [AI4Finance-LLC/FinRL-Library#65]
medium link: https://towardsdatascience.com/finrl-for-quantitative-finance-tutorial-for-multiple-stock-trading-7b00763b7530 9first colab link)
my colab link: https://colab.research.google.com/github/AI4Finance-LLC/FinRL-Library/blob/master/FinRL_multiple_stock_trading.ipynb
part 5, cell 18 is not working, says TypeError: __init__() got an unexpected keyword argument 'transaction_cost_pct'
when i comment it it says it needs two other vars.

**Comment by mikelty** [comment]
this also happened on the single stock colab notebook
medium link pointing to that: https://towardsdatascience.com/finrl-for-quantitative-finance-tutorial-for-single-stock-trading-37d6d7c30aac

**Comment by louisowen6** [comment]
I believe this happened due to the latest merge request. Currently, the parameter 'transaction_cost_pct' is changed to '`buy_cost_pct`' and '`sell_cost_pct`'.

**Comment by mikelty** [comment]
yeah i think that's why. thanks.
