### ISSUE TITLE
Usage for intraday trading

### ISSUE THREAD

**Issue by MOvi996** [AI4Finance-LLC/FinRL-Library#73]
How to use this library for intraday trading? It originally uses just daily data, but what if I need to make decisions at, let's say, hourly rate?

**Comment by XiaoYangLiu-FinRL** [comment]
Please treat the data as time series. For intraday trading, a change would be adding penalty for holding shares before the market closing.   Hourly is not a good set, let us consider minutes, than you may want to encourage selling, like the 30 minute window before the market closes.

**Comment by ensonario** [comment]
Thanks for your response @XiaoYangLiu-FinRL, what would be the best way to add such penatly?

**Comment by XiaoYangLiu-FinRL** [comment]
Adding a - frac * (values of shares) term would be good.  E.g., frac = t/T, where T = 30; t = 1, 2, 3, ..., 30.
