### ISSUE TITLE
reward is a large negative number

### ISSUE THREAD

**Issue by simin75simin** [AI4Finance-LLC/FinRL-Library#77]
I'm still quite new to this repo so correct me if i'm wrong but i think the reward for this environment cannot be less than the negated initial money (I saw there's reward scaling by roughly one in ten thousand but that does not make it less than the negated initial money either.) During training A2C using the default 100000 initial money, however, I saw this line:
total_reward       | -2.93e+20
Could you double check the environment or provide some explanation on the reward? Thanks.

**Comment by XiaoYangLiu-FinRL** [comment]
Can you try the Notebooks first?  This question is hard to answer, the context here can be wild.
