### ISSUE TITLE
error when i import finrl.env

### ISSUE THREAD

**Issue by jxin2618** [AI4Finance-LLC/FinRL-Library#81]
I  have installed successfully all the packages through FinRL library. However, I met an error when i import finrl.env in my code as follows.

from finrl.env.environment import EnvSetup
from finrl.env.EnvMultipleStock_train import StockEnvTrain
from finrl.env.EnvMultipleStock_trade import StockEnvTrade
Traceback (most recent call last):

  File "<ipython-input-25-fb9604d0fb88>", line 1, in <module>
    from finrl.env.environment import EnvSetup

ModuleNotFoundError: No module named 'finrl.env.environment'

I checked my site-package folder, and I found there are only 'env_stocktrading.py' and 'env_portfolio.py' under the folder of finrl.env.

What should I do to import the 'finrl.env.environment' and 'finrl.env.EnvMultipleStock_train'?

**Comment by Petcron** [comment]
Hi how did you get around this issue please?
I get the below error. If I rem out the EnvSetip line the error repeats on line 14.
I tried the install on fresh Python 3.6 and 3.8 environments.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-12-aa2060948676> in <module>
     11 from finrl.preprocessing.data import data_split
     12 # from finrl.env.environment import EnvSetup
---> 13 from finrl.env.EnvMultipleStock_train import StockEnvTrain
     14 from finrl.env.EnvMultipleStock_trade import StockEnvTrade
     15 from finrl.model.models import DRLAgent

ModuleNotFoundError: No module named 'finrl.env.EnvMultipleStock_train'

**Comment by jxin2618** [comment]
I found the function file elsewhere. Just put them under the path './site-packages/finrl/env/'

[env.zip](https://github.com/AI4Finance-LLC/FinRL-Library/files/5879628/env.zip)
