### ISSUE TITLE
Help to build working env

### ISSUE THREAD

**Issue by setar** [AI4Finance-LLC/FinRL-Library#85]
Hi, 
i can not build full working env :(
(win10 , python 3.6.5)

make please version dump for me.
pip freeze > requirements.txt

my actions:
`
git clone https://github.com/AI4Finance-LLC/FinRL-Library.git

cd FinRL-Library

virtualenv -p python3 venv

venv\Scripts\activate

(venv) pip install -r requirements.txt

(venv) pip install ipykernel

(venv) jupyter notebook

open any notebook, for example "FinRL_single_stock_trading.ipynb"

run

on 2.3 'Import Packages' i get errors:
`

C:\Users\setar\AppData\Roaming\Python\Python36\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
C:\Users\setar\AppData\Roaming\Python\Python36\site-packages\empyrical\utils.py:32: UserWarning: Unable to import pandas_datareader. Suppressing import error and continuing. All data reading functionality will raise errors; but has been deprecated and will be removed in a later version.
  warnings.warn(msg)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-702eb9662fbe> in <module>
     12 from finrl.env.env_stocktrading import StockTradingEnv
     13 from finrl.model.models import DRLAgent
---> 14 from finrl.trade.backtest import BackTestStats, BaselineStats, BackTestPlot
     15 
     16 import sys

D:\Nextcloud\projects\ai\FinRL\FinRL-Library\finrl\trade\backtest.py in <module>
      2 import numpy as np
      3 
----> 4 from pyfolio import timeseries
      5 import pyfolio
      6 import matplotlib.pyplot as plt

c:\program files\python36\lib\site-packages\pyfolio\__init__.py in <module>
----> 1 from . import utils
      2 from . import timeseries
      3 from . import pos
      4 from . import txn
      5 from . import interesting_periods

c:\program files\python36\lib\site-packages\pyfolio\utils.py in <module>
     26 import empyrical.utils
     27 
---> 28 from . import pos
     29 from . import txn
     30 

c:\program files\python36\lib\site-packages\pyfolio\pos.py in <module>
     20 
     21 try:
---> 22     from zipline.assets import Equity, Future
     23     ZIPLINE = True
     24 except ImportError:

~\AppData\Roaming\Python\Python36\site-packages\zipline\__init__.py in <module>
     22 
     23 from . import data
---> 24 from . import finance
     25 from . import gens
     26 from . import utils

~\AppData\Roaming\Python\Python36\site-packages\zipline\finance\__init__.py in <module>
     14 # limitations under the License.
     15 
---> 16 from . import execution, trading
     17 
     18 __all__ = [

~\AppData\Roaming\Python\Python36\site-packages\zipline\finance\trading.py in <module>
     18 
     19 from zipline.utils.memoize import remember_last
---> 20 from zipline.utils.pandas_utils import normalize_date
     21 
     22 log = logbook.Logger('Trading')

~\AppData\Roaming\Python\Python36\site-packages\zipline\utils\pandas_utils.py in <module>
    221 
    222 _INDEXER_NAMES = [
--> 223     '_' + name for (name, _) in pd.core.indexing.get_indexers_list()
    224 ]
    225 

AttributeError: module 'pandas.core.indexing' has no attribute 'get_indexers_list'`

**Comment by setar** [comment]
clean install docker also have errors in environment.
run 2.3 from FinRL_single_stock_trading.ipynb:

/opt/conda/lib/python3.6/site-packages/pyfolio/pos.py:27: UserWarning: Module "zipline.assets" not found; multipliers will not be applied to position notionals.
  'Module "zipline.assets" not found; multipliers will not be applied'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-b0ace5c9f8c0> in <module>
     12 from finrl.env.env_stocktrading import StockTradingEnv
     13 from finrl.model.models import DRLAgent
---> 14 from finrl.trade.backtest import backtest_stats, baseline_stats, backtest_plot
     15 
     16 import sys

ImportError: cannot import name 'baseline_stats'

**Comment by setar** [comment]
Now i  get  work environment:
make it via conda:
(base) root@kali:~# conda --version
conda 4.9.2
(base) root@kali:~# conda update conda
(base) root@kali:~# conda create --name FinRL python=3.6
(base) root@kali:~# conda info --envs
# conda environments:
#
base                  *  /root/anaconda3
FinRL                    /root/anaconda3/envs/FinRL
(base) root@kali:~#  conda activate FinRL
(FinRL) root@kali:~# conda install -c conda-forge zipline
(FinRL) root@kali:~# git clone https://github.com/AI4Finance-LLC/FinRL-Library.git
(FinRL) root@kali:~# cd FinRL-Library/
(FinRL) root@kali:~# pip install jupyter
(FinRL) root@kali:~# pip install --user ipykernel
(FinRL) root@kali:~# pip install -r requirements.txt
(FinRL) root@kali:~# jupyter-notebook --allow-root --ip 0.0.0.0

open notebook link in browser and work.

**Comment by wjhithit** [comment]
@setar it is lost according your edited
