### ISSUE TITLE
Function name mismatches

### ISSUE THREAD

**Issue by acertainKnight** [AI4Finance-LLC/FinRL-Library#86]
When running from main.py (or any of the notebooks), there seems to be a number of function calls which do not exist within the modules that they are called from. Many of these seem to be coming from backtest.py which appears to have renamed the functions. After just switching the names as a quick test, some additional errors arise during the train_one function with array mismatches.

**Comment by spencerR1992** [comment]
Thanks for your comment! We have changed the principal notebooks, and the functions were renamed to conform with PEP conventions!
