### ISSUE TITLE
No module named 'finrl.env.environment'

### ISSUE THREAD

**Issue by Petcron** [AI4Finance-LLC/FinRL-Library#88]
Hi I've created 2 fresh environments in Python 3.6 and 3.8. Both are giving the below error.

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-13-7e7fdd91f6de> in <module>
     10 from finrl.preprocessing.preprocessors import FeatureEngineer
     11 from finrl.preprocessing.data import data_split
---> 12 from finrl.env.environment import EnvSetup
     13 from finrl.env.EnvMultipleStock_train import StockEnvTrain
     14 from finrl.env.EnvMultipleStock_trade import StockEnvTrade

ModuleNotFoundError: No module named 'finrl.env.environment'

**Comment by XiaoYangLiu-FinRL** [comment]
Not follow. Could you please explain your situation more? Thx.

**Comment by Petcron** [comment]
I figured it out there was an issue in the stable baselines install I think.
I built everything from scratch and debugged from there.

**Comment by paulcarouge** [comment]
@Petcron I am experiencing the same problem when importing packages, could you explain in detail how you fixed the issue?
thank you!

**Comment by MrGod2U** [comment]
same issue as paulcarouge

**Comment by Petcron** [comment]
Hi a user (Jing Xi ) shared the attached zip.

You should save the extract to the anaconda path './site-packages/finrl/env/'.

This did fix the one issue and led to a couple of others, which related to environments

In the end I restarted from ground zero and it mostly worked.

Gluck
