### ISSUE TITLE
1 h dataset

### ISSUE THREAD

**Issue by pwner4810** [AI4Finance-LLC/FinRL-Library#9]
hi thanks for your article 
I used 1 h dataset from 2014 to 2020 of 3 stock with calculated turbulence but the model got confused with terrible result 
 this is models hyperparameters and the result 
print("==============Model Training===========")
a2c_params_tuning = {'n_steps':5, 
			  'ent_coef':0.005, 
			  'learning_rate':0.0002,
			  'verbose':0,
			  'timesteps':150000}
model_a2c = agent.train_A2C(model_name = "A2C_{}".format(now), model_params = a2c_params_tuning)

begin_total_asset:1000000
end_total_asset:199131.0821982477
total_reward:-800868.9178017523
total_cost:  4804.364243369928
total_trades:  40468
Sharpe:  -0.053885447004911706
=================================
Training time (A2C):  5.864342439174652  minutes

what's your opinion about implementing 1 hours data to model

**Comment by BruceYanghy** [comment]
> hi thanks for your article
> I used 1 h dataset from 2014 to 2020 of 3 stock with calculated turbulence but the model got confused with terrible result
> this is models hyperparameters and the result
> print("==============Model Training===========")
> a2c_params_tuning = {'n_steps':5,
> 'ent_coef':0.005,
> 'learning_rate':0.0002,
> 'verbose':0,
> 'timesteps':150000}
> model_a2c = agent.train_A2C(model_name = "A2C_{}".format(now), model_params = a2c_params_tuning)
> 
> # begin_total_asset:1000000
> end_total_asset:199131.0821982477
> total_reward:-800868.9178017523
> total_cost: 4804.364243369928
> total_trades: 40468
> Sharpe: -0.053885447004911706
> Training time (A2C): 5.864342439174652 minutes
> 
> what's your opinion about implementing 1 hours data to model

Did you use intraday hourly data? The current setting is for daily data.

**Comment by pwner4810** [comment]
yes i used hourly data . but for model setting  i haven't approached to the suitable result and all of them failed could you please suggest a appropriate   setting for hourly data 
thanks a lot

**Comment by BruceYanghy** [comment]
> yes i used hourly data with calculated turbulence index and indicator . but for agent setting i haven't approached to the suitable result and all of them failed could you please suggest a appropriate setting for hourly data
> thanks a lot

Can you tell me which 3 stocks you used? I have access to intraday data and even tick data, but it's not free.

**Comment by pwner4810** [comment]
yes of course AAPL ,MSFT,FB from 1.1.2014 up to now

**Comment by xiedidan** [comment]
I'm trying to train on minute data, got similar results...

```
{'n_steps': 2048,
 'ent_coef': 0.01,
 'learning_rate': 0.00025,
 'batch_size': 64,
 'verbose': 0,
 'timesteps': 500000}
```

```
begin_total_asset:100000
end_total_asset:9.412269923916398
total_reward:-99990.58773007608
total_cost:  99197.89260402077
total_trades:  221257
Sharpe:  -0.5482703628716898
```
