### ISSUE TITLE
"Backtest stats" name misalignment in files "finrl/autotrain/training.py" and "finrl/trade/backtest.py"

### ISSUE THREAD

**Issue by skybluejamie** [AI4Finance-LLC/FinRL-Library#90]
Ran into an error when running `python main.py --mode=train`:

- `BackTestStats` called in  "finrl/autotrain/training.py"
- Defined as function with name `backtest_stats` in "finrl/trade/backtest.py"

**Comment by skybluejamie** [comment]
`BackTestStats` also used in the jupyter notebooks. Haven't ran them yet, but guess they won't work.

**Comment by XiaoYangLiu-FinRL** [comment]
Agree. We made some updates, and now they are inconsistent. Would you please test them and help out here?  Thx.

**Comment by skybluejamie** [comment]
Yes, sure. I can make a PR to fix the inconsistencies if you give me permission?

**Comment by skybluejamie** [comment]
Yes, sure. Will create a PR.

**Comment by XiaoYangLiu-FinRL** [comment]
Sure. Thx.

**Comment by spencerR1992** [comment]
Closing for now, thanks
