### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'use_technical_indicator'

### ISSUE THREAD

**Issue by zcy-4747** [AI4Finance-LLC/FinRL-Library#93]
How can I solve this problem. I looked at the API, but it didn't work

# Perform Feature Engineering:
df = FeatureEngineer(df.copy(),
                      use_technical_indicator=True,
                      tech_indicator_list = config.TECHNICAL_INDICATORS_LIST,
                      use_turbulence=True,
                      user_defined_feature = False).preprocess_data()

**Comment by spencerR1992** [comment]
Hello! I believe that the implementation of the FeatureEngineer may have changed under you. Please pull the latest code and try again. If you encounter issues, please open another ticket.

**Comment by xanstorm** [comment]
Hi. I have the exact same error. I installed the latest version of Feature Engineer, but I get the error nonetheless. 
![Screen Shot 2021-03-12 at 2 12 59 PM](https://user-images.githubusercontent.com/7649650/110987461-198f5680-833d-11eb-9d0b-b005aebd43e9.jpg)

**Comment by xanstorm** [comment]
![Screen Shot 2021-03-12 at 2 42 10 PM](https://user-images.githubusercontent.com/7649650/110990310-257d1780-8341-11eb-9241-022340cf4579.jpg)
I also tried this installation.
